[hud]
	#Enable or disable the RPG Stats Overlay
	enableOverlay = true
	#X Offset from the right side of the screen
	# Default: 5
	# Range: 0 ~ 10000
	xOffset = 5
	#Y Offset from the bottom of the screen
	# Default: 10
	# Range: 0 ~ 10000
	yOffset = 10
